package generator

import (
	"text/template"
)

type TemplateName = string

const tmplInterface TemplateName = "tmplInterface"
const tmplMethod TemplateName = "tmplMethod"
const tmplMethodBody TemplateName = "tmplMethodBody"

var templates = template.Must(
	template.New("Templates").
		Funcs(template.FuncMap{
			"ParseQueries":    parseQueries,
			"ParseHeaders":    parseHeaders,
			"ParsePathParams": parsePathParams,
		}).
		Parse(`
// CODE GENERATED BY genapi. DO NOT EDIT.
package {{.Package}}

{{range .Interfaces}}
{{template "tmplInterface" .}}
{{end}}
`))

func init() {
	template.Must(templates.New(tmplInterface).Parse(`
{{- $impl := printf "impl%s" .Name}}
type {{ $impl }} struct {
	client genapi.HttpClient
}

// setHttpClient implments genapi.Interface
func (i *{{ $impl }}) setHttpClient(client genapi.HttpClient) {
	i.client = client
}

{{range .Methods}}
{{template "tmplMethod" .}}
{{end}}
`))

	template.Must(templates.New(tmplMethod).Parse(`
func (i *impl{{ .Interface }}) {{ .Name }}(
{{- range $i, $p := .Params }}
    {{- if $i }}, {{ end }}{{ $p.Name }} {{ $p.Type }}
{{- end -}}
)
{{- if gt (len .Results) 1 }}({{- end -}}
    {{- range $i, $r := .Results }}
    {{- if $i }}, {{ end }}{{ $r.Name }} {{ $r.Type }}
    {{- end -}}
{{- if gt (len .Results) 1 }}){{- end -}}
{{- " " -}}
{
{{- template "tmplMethodBody" . -}}
}
`))

	template.Must(templates.New(tmplMethodBody).Parse(`
	i.client.Do(&genapi.Request{
		{{- with .Annotations.RequestLine.Method -}}
		Method: "{{.}}",
		{{- end -}}
		{{- with .Annotations.RequestLine.Path -}}
		Path:   "{{.}}",
		{{- end -}}
		{{- if .Annotations.RequestLine.PathParams -}}
		PathParams: {{ ParsePathParams . }},
		{{- end -}}
		{{- with .Annotations.Queries -}}
		Queries: {{ ParseQueries . }},
		{{- end -}}
		{{- with .Annotations.Headers -}}
		Headers: {{ ParseHeaders . }},
		{{- end -}}
		{{- with .BindingParams.Context -}}
		Context: {{.Name}},
		{{- end -}}
		{{- with .BindingParams.Body -}}
		Body: {{.Name}},
		{{- end -}}
	})
    `))
}

// TODO: 2. Headers - done
// TODO: 3. Path Params
// TODO: 4. Body
// TODO: 5. Handle Result
// TODO: Fill all fieds of Request with default value
